main: com.alazeprt.APRandomTeleport
name: APRandomTeleport
version: 2.0-PRE-2
api-version: 1.13
description: A random teleport plugin
author: alazeprt
commands:
  rtp:
    description: A random teleport command
permissions:
  aprtp.use:
    description: Use /rtp Command
    default: true
  aprtp.world:
    description: Use /rtp world <world> Command
    default: op
  aprtp.world.*:
    description: Use /rtp world <world> Command(All Worlds)
    default: op
  aprtp.command.help:
    description: Use /rtp help Command
    default: true
  aprtp.command.reload:
    description: Use /rtp reload Command
    default: op
  aprtp.bypass:
    description: Can skip random teleport cooldown time
    default: op
  aprtp.forceplayer:
    description: Use /rtp player Command
    default: op
  aprtp.player:
    description: Contains basic permissions
    children:
      aprtp.use: true
      aprtp.command.help: true
  aprtp.admin:
    description: Have all permissions
    default: op
    children:
      aprtp.player: true
      aprtp.world.*: true
      aprtp.command.reload: true
      aprtp.bypass: true
      aprtp.forceplayer: true
  aprtp.*:
    description: Have all permissions
    default: op
    children:
      aprtp.admin: true